# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [40]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np
from scipy.spatial import distance

In [29]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
df

,name,type_1,type_2,hp,attack,defense,sp._atk,sp._def,speed,generation,legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [30]:
# we set our significance level
alpha = 0.05

hp_dragon = df[df['type_1'] == 'Dragon']['hp']
hp_grass = df[df['type_1'] == 'Grass']['hp']

t_stat, p_value = st.ttest_ind(hp_dragon, hp_grass, equal_var=False, alternative='greater')

display(t_stat, p_value)

np.float64(3.3349632905124063)

np.float64(0.0007993609745420599)

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [31]:
# independent t-test

legendary = df[df['legendary'] == True]
non_legendary = df[df['legendary'] == False]

stats_list = ['hp', 'attack', 'defense', 'sp._atk', 'sp._def', 'speed']

alpha = 0.05

for stat in stats_list:
    legendary_groupped = legendary[stat].dropna()
    non_legendary_grupped = non_legendary[stat].dropna()

    t_stat, p_value = st.ttest_ind(legendary_groupped, non_legendary_grupped, equal_var=False)


    print(f"\n Stats: {stat}")
    print(f"   p-value: {p_value:.15f}")

    if p_value < 0.05:
        print("  We reject the H0 hypotesis.")
        print("  there is evidence that legendary and non-legendary pokemon have similar "+ stat +" ")
    else:
        print("  We do not reject the H0 hypotesis")
        print("  there is not enough evidence that the " + stat + " are different between both groups")

 Stats: hp
   p-value: 0.000000000000100
  We reject the H0 hypotesis.
  there is evidence that legendary and non-legendary pokemon have similar hp

 Stats: attack
   p-value: 0.000000000000000
  We reject the H0 hypotesis.
  there is evidence that legendary and non-legendary pokemon have similar attack

 Stats: defense
   p-value: 0.000000000048270
  We reject the H0 hypotesis.
  there is evidence that legendary and non-legendary pokemon have similar defense

 Stats: sp._atk
   p-value: 0.000000000000000
  We reject the H0 hypotesis.
  there is evidence that legendary and non-legendary pokemon have similar sp._atk

 Stats: sp._def
   p-value: 0.000000000000002
  We reject the H0 hypotesis.
  there is evidence that legendary and non-legendary pokemon have similar sp._def

 Stats: speed
   p-value: 0.000000000000000
  We reject the H0 hypotesis.
  there is evidence that legendary and non-legendary pokemon have similar speed

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [45]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head(25)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0
10,-114.60,33.62,16.0,3741.0,801.0,2434.0,824.0,2.6797,86500.0
11,-114.60,33.60,21.0,1988.0,483.0,1182.0,437.0,1.6250,62000.0
12,-114.61,34.84,48.0,1291.0,248.0,580.0,211.0,2.1571,48600.0
13,-114.61,34.83,31.0,2478.0,464.0,1346.0,479.0,3.2120,70400.0
14,-114.63,32.76,15.0,1448.0,378.0,949.0,300.0,0.8585,45000.0
15,-114.65,34.89,17.0,2556.0,587.0,1005.0,401.0,1.6991,69100.0
16,-114.65,33.60,28.0,1678.0,322.0,666.0,256.0,2.9653,94900.0
17,-114.65,32.79,21.0,44.0,33.0,64.0,27.0,0.8571,25000.0
18,-114.66,32.74,17.0,1388.0,386.0,775.0,320.0,1.2049,44000.0
19,-114.67,33.92,17.0,97.0,24.0,29.0,15.0,1.2656,27500.0
20,-114.68,33.49,20.0,1491.0,360.0,1135.0,303.0,1.6395,44400.0
21,-114.73,33.43,24.0,796.0,243.0,227.0,139.0,0.8964,59200.0
22,-114.94,34.55,20.0,350.0,95.0,119.0,58.0,1.6250,50000.0
23,-114.98,33.82,15.0,644.0,129.0,137.0,52.0,3.2097,71300.0
24,-115.22,33.54,18.0,1706.0,397.0,3424.0,283.0,1.6250,53500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [51]:
# Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.

def distance_calculator(longitude, latitude):

    school_coord = (-114.40, 34.00)
    hospital_coord = (-114.50, 33.80)

    house_coord = (longitude, latitude)

    school_dist = distance.euclidean(house_coord, school_coord)
    hospital_dist = distance.euclidean(house_coord, hospital_coord)

    return school_dist, hospital_dist

In [52]:
school_dist, hospital_dist = distance_calculator(34.19, -114.31)

print(f"distance to school: {school_dist}")
print(f"distance to hospital: {hospital_dist}")

distance to school: 209.94009669427135
distance to hospital: 209.8696933813932

In [70]:
# Divide your dataset into houses close and far from either a hospital or school.

school_coord = (-118, 34)
hospital_coord = (-122, 37)

CLOSE = 0.5

df_new = pd.DataFrame()
df_new["house"] = [f"house{i+1}" for i in range(len(df))]
df_new["longitude"] = df["longitude"]
df_new["latitude"] = df["latitude"]
df_new["median_house_value"] = df["median_house_value"]

df_new["dist_eucl_school"] = df_new.apply( lambda row: distance.euclidean((row["longitude"], row["latitude"]), school_coord), axis=1)

df_new["dist_eucl_hospital"] = df_new.apply( lambda row: distance.euclidean((row["longitude"], row["latitude"]), hospital_coord), axis=1)

df_new["close_to_school"] = df_new["dist_eucl_school"] < CLOSE
df_new["close_to_hospital"] = df_new["dist_eucl_hospital"] < CLOSE

display(df_new)

,house,longitude,latitude,median_house_value,dist_eucl_school,dist_eucl_hospital,close_to_school,close_to_hospital
0,house1,-114.31,34.19,66900.0,3.694888,8.187319,False,False
1,house2,-114.47,34.40,80100.0,3.552591,7.966235,False,False
2,house3,-114.56,33.69,85700.0,3.453940,8.143077,False,False
3,house4,-114.57,33.64,73400.0,3.448840,8.154416,False,False
4,house5,-114.57,33.57,65500.0,3.456848,8.183508,False,False
...,...,...,...,...,...,...,...,...
16995,house16996,-124.26,40.58,111400.0,9.082070,4.233675,False,False
16996,house16997,-124.27,40.69,79000.0,9.168915,4.332320,False,False
16997,house16998,-124.30,41.84,103600.0,10.057614,5.358694,False,False
16998,house16999,-124.30,41.80,85800.0,10.026465,5.322593,False,False
16999,house17000,-124.35,40.54,94600.0,9.115597,4.249012,False,False

In [71]:
close_condition = df_new["close_to_school"] | df_new["close_to_hospital"]

df_close_to_any = df_new[close_condition]
df_close_to_none = df_new[~close_condition]

display(df_close_to_any)

,house,longitude,latitude,median_house_value,dist_eucl_school,dist_eucl_hospital,close_to_school,close_to_hospital
2366,house2367,-117.51,34.00,124700.0,0.490000,5.400009,True,False
2367,house2368,-117.51,33.97,137500.0,0.490918,5.416733,True,False
2368,house2369,-117.51,33.95,169100.0,0.492544,5.427946,True,False
2371,house2372,-117.52,33.99,182900.0,0.480104,5.397268,True,False
2372,house2373,-117.52,33.89,220800.0,0.492443,5.453668,True,False
...,...,...,...,...,...,...,...,...
15090,house15091,-122.25,37.08,177500.0,5.248705,0.262488,False,True
15170,house15171,-122.26,37.38,500001.0,5.438014,0.460435,False,True
15253,house15254,-122.27,37.32,277700.0,5.408817,0.418688,False,True
15254,house15255,-122.27,37.24,319400.0,5.360084,0.361248,False,True
15686,house15687,-122.38,37.18,286100.0,5.412652,0.420476,False,True

In [72]:
#Choose the propper test and, with 5% significance, comment your findings ---> Student's t-test

mean_price_close = df_close_to_any["median_house_value"].mean()
media_precio_lejos = df_close_to_none["median_house_value"].mean()

prices_close = df["median_house_value"]
prices_far = df["median_house_value"]

t_stat, p_valor = stats.ttest_ind(
    prices_close, prices_far, equal_var=False
)

print(f" t-stats: {t_stat:.4f}")
print(f"p-valor: {p_valor}")

 t-stats: 0.0000
p-valor: 1.0

In [73]:
variable = "median_house_value"

for stat in stats_list:
 group_close = df_close_to_any[variable].dropna()
 group_far = df_close_to_none[variable].dropna()
    
 t_stat, p_value = stats.ttest_ind(group_close, group_far, equal_var=False)
    
print(f"Variable result: {variable}")
print(f"  t-value : {t_stat:.4f}")
print(f"  p-value: {p_value:.8f}")


    
if p_value < 0.05:
        print("   We reject the H0 hypotesis.")
        print("   There is statistically significant evidence to conclude that homes that are close to a school or a hospital have a different economic value compared to those that are far away.")
else:
        print("   The null hypothesis (H0) is not rejected.")
        print("   Finding: There is not enough statistical evidence to conclude that proximity to a school or a hospital influences the value of homes.")

Variable result: median_house_value
  t-value : 37.9923
  p-value: 0.00000000
   We reject the H0 hypotesis.
   There is statistically significant evidence to conclude that homes that are close to a school or a hospital have a different economic value compared to those that are far away.